export const SELECT_APPLICANT_SUCCESS = "SELECT_APPLICANT_SUCCESS";
export const REMOVE_APPLICANT_SUCCESS = "REMOVE_APPLICANT_SUCCESS";
export const VIEW_POSITION = "VIEW_POSITION";
export const SWITCH_POSITIONS = "SWITCH_POSITIONS";
