AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/{assets,tasks}/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false
