AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/{assets,tasks}/*'
    - 'test/**/*'
    - 'frontend/**/**'
    - 'script/**/**'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
