#!/bin/bash
docker-compose down
docker-compose build
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
docker-compose exec frontend sh -c "yarn build"
cp -a frontend/build/. api/public/
docker-compose exec api sh -c "rails db:migrate"
