#!/bin/bash
cp prod.env .env 
docker-compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans
docker-compose -f docker-compose.frontend.yml up --build --force-recreate
cp -a frontend/build/. backend/public/
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build --force-recreate -d