#!/bin/bash
docker-compose down
docker-compose -f docker-compose.frontend.yml up --build
docker run frontend:latest yarn build
cp -a frontend/build/. api/public/
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
docker-compose exec api sh -c "rails db:migrate"
