#!/bin/bash
docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
cp dev.env .env 
echo 'Please go to localhost:8000 for frontend' > ./api/public/index.html
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build


