export const CREATE_NEW_POSITION_SUCCESS = "CREATE_NEW_POSITION_SUCCESS";
export const IMPORT_NEW_POSITION_FAILURE = "IMPORT_NEW_POSITION_FAILURE";
export const IMPORT_NEW_POSITION_SUCCESS = "IMPORT_NEW_POSITION_SUCCESS";
export const IMPORT_NEW_POSITION_RESULT = "IMPORT_NEW_POSITION_RESULT";