export const UPDATE_POSITION_VALUE_REQUEST = "UPDATE_POSITION_VALUE_REQUEST"
export const UPDATE_POSITION_VALUE_SUCCESS = "UPDATE_POSITION_VALUE_SUCCESS"
export const UPDATE_POSITION_VALUE_ERROR = "UPDATE_POSITION_VALUE_ERROR"
