export const UPSERT_MATCH = "UPSERT_MATCH";
export const BATCH_UPSERT_MATCHES = "BATCH_UPSERT_MATCHES";
export const UPSERT_GUARANTEE = "UPSERT_GUARANTEE";
export const BATCH_UPSERT_GUARANTEES = "BATCH_UPSERT_GUARANTEES";
export const UPSERT_NOTE = "UPSERT_NOTE";
export const BATCH_UPSERT_NOTES = "BATCH_UPSERT_NOTES";
export const SET_SELECTED_POSITION = "SET_SELECTED_POSITION";
export const SET_VIEW_TYPE = "SET_VIEW_TYPE";
