import {
    Position,
    Applicant,
    Assignment,
    Application,
} from "../../../api/defs/types";

// stored in redux
export type RawMatch = {
    utorid: string;
    positionCode: string;
    stagedHoursAssigned?: number;
    stagedAssigned?: boolean;
    starred?: boolean;
    hidden?: boolean;
};

export type AppointmentGuaranteeStatus = {
    utorid: string;
    minHoursOwed: number;
    maxHoursOwed: number;
    previousHoursFulfilled: number;
};

// created by a selector
export type ApplicantSummary = {
    applicant: Applicant;
    application: Application | null;
    matches: MatchableAssignment[]; // generated by looking over RawMatches
    guarantee: AppointmentGuaranteeStatus | null;
    note: string | null;
};

export type MatchableAssignment = {
    position: Position;
    applicant: Applicant;
    hoursAssigned: number;
    status: MatchStatus;
};

export type PositionSummary = {
    position: Position;
    hoursAssigned: number; // calculated via assignments + matchable assignments
    filledStatus: FillStatus;
    applicantSummaries: ApplicantSummary[];
};

export type ApplicantViewMode = "table" | "grid";
export type MatchStatus =
    | "applied"
    | "starred"
    | "staged-assigned"
    | "assigned"
    | "hidden";
export type FillStatus = "empty" | "under" | "matched" | "over";
